
# Site settings
title: "Top 5 Deals"
title-font-size: '2.75em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: norcads@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Display Top 5 curated list of deals that you can find and buy on the web.
#baseurl: "/vyaasa"  the subpath of your site, e.g. /blog
url: "https://top5deals.netlify.app" # the base hostname & protocol for your site

permalink: :title/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 11
paginate_path: /page:num/


# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

#CSS
sass:
  style: compressed


include: [_pages]


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap